// 特权助手：固定形状的字体移除/还原脚本（ADR-0013）。只接受白名单字体名，路径锚定 Fonts 目录。
export const ELEVATED_FONT_SCRIPT = [
"param([string]$ArgsPath, [string]$MarkerPath)",
"$ErrorActionPreference = 'Continue'",
"try {",
"  $args = Get-Content -LiteralPath $ArgsPath -Raw | ConvertFrom-Json",
"  $fontsDir = Join-Path $env:SystemRoot 'Fonts'",
"  $pendingReboot = @()",
"  if ($args.mode -eq 'remove') {",
"    $names = @($args.fonts)",
"    foreach ($name in $names) {",
"      if ($name -notmatch '^[\\w.-]+\\.(ttf|ttc)$') { throw ('invalid font name: ' + $name) }",
"    }",
"    foreach ($name in $names) {",
"      $full = Join-Path $fontsDir $name",
"      if (Test-Path -LiteralPath $full) {",
"        try { Remove-Item -LiteralPath $full -Force -ErrorAction Stop }",
"        catch { $pendingReboot += $name }",
"      }",
"    }",
"    $fontKey = 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts'",
"    foreach ($v in (Get-Item $fontKey).Property) {",
"      $data = (Get-ItemProperty $fontKey -Name $v).$v",
"      if ($data -and ($names -contains [IO.Path]::GetFileName([string]$data))) {",
"        try { Remove-ItemProperty $fontKey -Name $v -ErrorAction Stop } catch {}",
"      }",
"    }",
"    if ($pendingReboot.Count -gt 0) {",
"      $key = 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager'",
"      $existing = @((Get-ItemProperty $key -Name PendingFileRenameOperations -ErrorAction SilentlyContinue).PendingFileRenameOperations)",
"      $entries = @()",
"      foreach ($name in $pendingReboot) { $entries += ('\\??\\' + (Join-Path $fontsDir $name)); $entries += '' }",
"      Set-ItemProperty $key -Name PendingFileRenameOperations -Value ($existing + $entries) -Type MultiString",
"    }",
"    @{ ok = $true; pendingReboot = $pendingReboot } | ConvertTo-Json | Set-Content -LiteralPath $MarkerPath -Encoding utf8",
"  } elseif ($args.mode -eq 'restore') {",
"    $backupDir = [string]$args.backupDir",
"    if (-not (Test-Path -LiteralPath $backupDir)) { throw 'backup dir missing' }",
"    Copy-Item -Path (Join-Path $backupDir '*') -Destination $fontsDir -Force",
"    if ($args.regFile -and (Test-Path -LiteralPath ([string]$args.regFile))) {",
"      & reg.exe import ([string]$args.regFile) | Out-Null",
"    }",
"    @{ ok = $true; pendingReboot = @() } | ConvertTo-Json | Set-Content -LiteralPath $MarkerPath -Encoding utf8",
"  } else { throw 'unknown mode' }",
"} catch {",
"  @{ ok = $false; error = $_.Exception.Message } | ConvertTo-Json | Set-Content -LiteralPath $MarkerPath -Encoding utf8",
"}",
].join("\n");
